FROM node:16-alpine
RUN npm config set registry https://registry.npmmirror.com/

WORKDIR .
COPY ./tencent-cloud.ts .
COPY ./global.config.ts .

WORKDIR /monopoly-server
COPY ./monopoly-server .
RUN npm install

EXPOSE 84
EXPOSE 85
CMD ["npm", "run", "start"]