FROM node:16-alpine

WORKDIR .
COPY ./global.config.ts .

WORKDIR /fatpaper-user-server
COPY ./fatpaper-user-server .
RUN npm config set registry https://registry.npmjs.org/ && npm install

EXPOSE 83
CMD ["npm", "run", "start"]