FROM node:16-alpine

WORKDIR .
COPY ./global.config.ts .

WORKDIR /monopoly-server
COPY ./monopoly-server .
RUN npm config set registry https://registry.npmjs.org/ && npm install

EXPOSE 84
EXPOSE 85
CMD ["npm", "run", "start"]